# PROJECT- INX Future Inc Employee Performance 

- Candidate Name : SWETA RAI
- Candidate E-Mail : swetaraibms1998@gmail.com
- Project Code : 10281
- Assessment ID :E10901-PR2-V18
- REP Name : DataMites™ Solutions Pvt Ltd
- Module : Certified Data Scientist - Project
- Exam Format : Open Project- IABAC™ Project Submission
- Project Assessment : IABAC™
- Registered Trainer : ASHOK KUMAR A
- Project Starting Date : 7-April-2023
- Submission Deadline Date: 17-April-2023

# SUMMARY OF THE PROJECT-

## BUSINESS CASE-

- INX Future Inc , (referred as INX ) , is one of the leading data analytics and automation solutions provider
  with over 15 years of global business presence. INX is consistently rated as top 20 best employers past 5
  years. 
- INX human resource policies are considered as employee friendly and widely perceived as best
  practices in the industry.
  Recent years, the employee performance indexes are not healthy    and this is becoming a growing
  concerns among the top management. There has been increased escalations on service delivery and
  client satisfaction levels came down by 8 percentage points.
  CEO, Mr. Brain, knows the issues but concerned to take any     actions in penalizing non-performing
  employees as this would affect the employee morale of all the employees in general and may further
  reduce the performance. Also, the market perception best employer and thereby attracting best talents
  to join the company.
- Mr. Brain decided to initiate a data science project , which analyses the current employee data and find
  the core underlying causes of this performance issues. Mr. Brain, being a data scientist himself, expects
  the findings of this project will help him to take right course of actions. He also expects a clear indicators
  of non performing employees, so that any penalization of non-performing employee, if required, may
  not significantly affect other employee morals

# PROBLEM STATEMENT-

- As per the business case, in the recent years the employee performance indexes are not healthy  and the client's satisfaction levels came down by 8 percentage points so in order to increase the business, the company is actively looking to initiate a data science project to analyse the performance rating of the employees to get a clear indication about the factors which are affecting the performance rating of the employees and also to analyse which group of employees are performing well and which are not.
- It is a multiclass classification problem, as the problem statement is to find out the performance rating.

# Requirement

- This IABAC project include a dummy data shared by IABAC for project analysis, in which the data source is IABAC™.
- INX Future Inc , (referred as INX ), is one of the leading data analytics and automation solutions provider with over 15 years of global business presence. INX is consistently rated as top 20 best employers past 5 years.The data is based on INX Future Inc.
- INX is consistently rated as top 20 best employers past 5 years.
- The entire project was done in multiple platforms which includes Jupiter notebook and VSCode with python platform.

# Analysis of the data

- Initially domain analysis was done for each and every features for better understanding of the features.
- By undergoing some basic checks, it was found that the data consist of both numerical and categorical features.

**INTERPRETING THE DATA**

**Numerical features includes**
- Age
- DistanceFromHome
- EmpEducationLevel
- EmpEnvironmentSatisfaction
- EmpHourlyRate
- EmpJobInvolvement
- EmpJobLevel
- EmpJobSatisfaction
- NumCompaniesWorked,
- EmpLastSalaryHikePercent
- EmpRelationshipSatisfaction
- TotalWorkExperienceInYears,
- TrainingTimesLastYear,
- EmpWorkLifeBalance
- ExperienceYearsAtThisCompany
- ExperienceYearsInCurrentRole
- YearsSinceLastPromotion
- YearsWithCurrManager

**Categorical features includes**
- Gender
- EducationBackground
- MaritalStatus
- EmpDepartment
- EmpJobRole
- BusinessTravelFrequency
- OverTime
- Attrition

**Exploratory data analysis was done for better understanding and to draw necessary insights from the data.**


# DATA

**External**

- The data was extracted from the link provided by IABAC.
- This data is from INX future Inc, where they wanted to explore Machine learning in order to benifit their organization.
- The provider had demanded certain reports that need to be speecified and executed.

**Processed**

- Various Visualization Techniques as well as Pre-processing techniques were used to transform the raw dataset into a proper model building dataset.
- The dataset underwent many analysis process in order to extract 

**Raw**

- This dataset was in raw excel form.
- This data set had a collection of Employee details such as (Age,Gender,job role, etc)
- This Raw data set has 1200 rows and 28 columns

# Jupyter Notebook
- The Jupyter Notebook is a web-based interactive computing platform. The notebook combines live code, equations, narrative text, visualizations.
- The jupyter notebook is used in this project.

# Tools and Libraries used

- **Numpy** - NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working 

- **Pandas** - Pandas is a Python library used for working with data sets. It has functions for analyzing, cleaning, exploring, and manipulating data. The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

- **Matplotlib** is a comprehensive library for creating static, animated, and interactive visualizations in Python.Matplotlib is an amazing visualization library in Python for 2D plots of arrays. Matplotlib is a multi-platform data visualization library.

- **Seaborn** - Seaborn is a Python data visualization library and open source libray based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical.

- **Scikit-learn** - Scikit-learn is an open source data analysis library, and the gold standard for Machine Learning (ML) in the Python ecosystem.scikit-learn is a Python module for machine learning built on top of SciPy and is distributed under the 3-Clause BSD license.

- **Scipy** -SciPy stands for Scientific Python. It provides more utility functions for optimization, stats and signal processing. Like NumPy, SciPy is open source.

# Insights expected from this project

**Department wise performances**
- Higher performance indicates 1 and lower performance indicates 0
- Report shows that the development department has highest           performance rating of 3 i.e higher performance rating
- Among all the departments data science has the lowest perfromance   rating of 2 and 4. This indicates that the employees in data       science department have average performance rating.
- In almost all the departments, the performance rating 3 is highly   seen and the performancee rating 4 is rarely seen.
- However the performance rating 4 is seen in Sales, Development     and Research and development department and not comparatively       less seen in Human resource, Data science and Finance.
- So, in order to bring up good performance of the EmpDepartment, 
  Sales, Development and Research and development department should   be taken care of.
  
**Top 3 Important Factors effecting employee performance**
- EmpSatisfaction
- ExperienceYearsAtThisCompany
- YearsSinceLastPromotion

**A trained model which can predict the employee performance based on factors as inputs. This
will be used to hire employees**
- To predict the performance of the employees the following models can be considered.

- **Support Vector Machine(calssifier)**- 98.99%(training accuracy),92.6%(testing accuracy)
- **Decision Tree(tuned)** 98.04%(training accuracy), 96.33%(testing accuracy)
- **Random Forest(tuned)** - 99.46%(training accuracy), 96.33%(testing accuracy)
- **Gradient boosting** - 99.66(training accuracy), 97.0%(testing accuracy)

**Recommendations to improve the employee performance based on insights from analysis**
- Creating an environment by giving flexible working hours.
- focus on these things in order to boost up performance of employees, as such employees will give excellent performance, more in numbers.
- Creating positive envirnoment int he company.
- Refreshment area and many more fun activities.
- Promote Employees more often in order to make them feel more job oriented.

# PrettyTable is created to analyse the test and train scores

In [1]:
from prettytable import PrettyTable
x=PrettyTable()
y=PrettyTable()

x.field_names = ["Model(Train)", "f1_score","accuracy","precision","recall"]
x.add_row(["Gradient Boosting", "99.66",'99.66','99.73','99.59'])
x.add_row(["Decision Tree(tuned)", "98.03",'98.04','98.77','97.30'])
x.add_row(["Random Forest(tuned)", "99.46",'99.46','99.32','99.59'])
x.add_row(["Support Vector Machine(calssifier)", "98.98",'98.99','99.86','98.11'])



y.field_names = ["Model(Test)", "f1_score","accuracy","precision","recall"]
y.add_row(["Gradient Boosting", "98.27",'97.0','98.84','97.71'])
y.add_row(["Decision Tree(tuned)", "97.88",'96.33','99.21','96.57'])
y.add_row(["Random Forest(tuned)", "97.90",'96.33','98.09','97.71'])
y.add_row(["Support Vector Machine(calssifier)", "95.81",'92.6','95.81','95.81'])



print(x)
print(y)

+------------------------------------+----------+----------+-----------+--------+
|            Model(Train)            | f1_score | accuracy | precision | recall |
+------------------------------------+----------+----------+-----------+--------+
|         Gradient Boosting          |  99.66   |  99.66   |   99.73   | 99.59  |
|        Decision Tree(tuned)        |  98.03   |  98.04   |   98.77   | 97.30  |
|        Random Forest(tuned)        |  99.46   |  99.46   |   99.32   | 99.59  |
| Support Vector Machine(calssifier) |  98.98   |  98.99   |   99.86   | 98.11  |
+------------------------------------+----------+----------+-----------+--------+
+------------------------------------+----------+----------+-----------+--------+
|            Model(Test)             | f1_score | accuracy | precision | recall |
+------------------------------------+----------+----------+-----------+--------+
|         Gradient Boosting          |  98.27   |   97.0   |   98.84   | 97.71  |
|        Decisio

- **Gradient boosting** - 99.66(training accuracy),97.0%(testing accuracy)
- **Decision Tree(tuned)** 98.04%(training accuracy),96.33%(testing accuracy)
- **Random Forest(tuned)** - 99.46%(training accuracy),96.33%(testing accuracy)
- **Support Vector Machine(calssifier)**- 98.99%(training accuracy),92.6%(testing accuracy)

# Exploratory data analysis

# UNIVARIATE ANALYSIS:-
- Univariate analysis is a form of analysis that only involves a single variable.It means the analysis of a single variable (or column) in a dataset.
- Univariate analysis is the simplest kind of data analysis in the field of statistics.
- Univariate analysis explores each variable in a data set, separately. It looks at the range of values, as well as the central tendency of the values. It describes the pattern of response to the variable. It describes each variable on its own.Descriptive statistics describe and summarize data. Univariate descriptive statistics describe individual variables.
- For better understanding and visualisation of the data the bivariate and the multivariate analysis is used.

###### VISUALIZATION OF CONTINUOUS FEATURES:-

**continuous features:**- It takes any measured value within a specific range. Continuous features can be visualized using different plot mentioned below.
- Histogram: A histogram is a graph used to show frequency distribution where data are grouped into continuous ranges and each range corresponds to a vertical bar. The horizontal axis represents the number range while the vertical axis represents the amount of data that is present in a range.

###### VISUALIZATION OF DISCRETE AND CATEGORICAL FEATURES:-

**Discrete and Categorical:**- Discrete features takes specific countable values. Categorical data is a type of data that is used to group information with similar characteristics.
-Discrete features can be visualized using different plots mentioned below.
- Countplot: A Countplot is used to represent the counts of observations in each categorical variables using bars.


# BIAVARIATE ANALYSIS

- Bivariate analysis is one of the simplest forms of quantitative (statistical) analysis. It involves the analysis of two variables (often denoted as X, Y), for the purpose of determining the empirical relationship between them.
- In order words, it is meant to determine any concurrent relationship between different variables and finally to extract relevant relationships for better understanding of the data

### BARPLOT
- A barplot (or barchart) is one of the most common types of graphic. It shows the relationship between a numeric and a categoric variable. Each entity of the categoric variable is represented as a bar. The size of the bar represents its numeric value.

### Lineplot
- A line plot is a type of plot in Seaborn that shows the relationship between two continuous variables by connecting the data points with a straight line.

# MULTIVARIANT ANALYSIS:-

- Multiple regression is the most commonly utilized multivariate technique. It examines the relationship between a single metric dependent variable and two or more metric independent variables.

- In this project, a detailed exploratory data analysis was done on the data.Exploratory data analysis was done through various charts, plots, graphs to find out the relationship between the numerical-categorical features and also numerical-numerical features.
- Also, EDA was done on both Continous and Numerical features.
- To find out the distribution of the features the distplot was used, it is important is check the distribution of the data for outlier handling and also for imputing the missing values.
- This particular dataset doesn't have any missing values in it nor it has any duplicate records.

# SUMMARY OF EXPLORATORY DATA ANALYSIS

- The male and female employees work life balance are almost same for both the gender.
- When the employees have received YearsSinceLastPromotion more than 2.0, the employees are not leaving the company.
- when the employees have received YearsSinceLastPromotion less than 2.0, the employees are leaving the company.
- Data science employees has the lowest experience years in current role.
- The employees job role Manager has the highest experience years in current role followed by Research Director.
- Technical Architect has the lowest experience years in current role.
- The Human Resources has the highest Employee job involvement.
- Technical degree and other has the lowest Employee job involvement.
- The employees working in the Human resources educational background has worked in more than 3 companies.
- The male employees are more frequent to leave the job.
- The EmpLastSalaryHikePercent between 22 and 24 has the highest YearsSinceLastPromotion when the performance rating is 4
- The EmpLastSalaryHikePercent between 22 and 24 has the highest YearsSinceLastPromotion when the performance rating is 3
- The EmpLastSalaryHikePercent between 22 and 24 has the highest YearsSinceLastPromotion when the performance rating is 2
- The maximum YearsSinceLastPromotion is between 0 to 6 for all the performance rating

# STATISTICAL ANALYSIS OF THE DATA

**Basic checks-**
- Various basic checks such as checking the shape and size of the data,checking the missing values, checking the duplicate records was done successfully.
- It was found that there were no missing values, no duplicate records and also no constant values in the features.

**Distribution of continuous features.**
- Distribution can be divided into normal distribution and skewed distribution.
- The age feature was considered as Normally distributed feature.
- The features DistanceFromHome,EmpLastSalaryHikePercent,TotalWorkExperienceInYears,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole, YearsSinceLastPromotion,YearsWithCurrManager are skewed distribution i.e Right skewed also known as Positive skewed distribution.

**DEPARTMENT WISE PERFORMANCE RATING**

- Barplot,violinplot are used to bring out neccessary insights from the particular features.

- **OBSERVATION-**

- EmpDepartment Development department shows High performance rating as shown in the above graphs

- Sales: The Performace rating level 3 is maximum in the sales department. The male employees performance rating is higher than the female employees.The employees not leaving the company is higher.

- Human Resources: The Performace rating level 3 is maximum in the Human resource department.The female employee rating is higher than the male employees. The employees not leaving the company is higher.

- Development: The performance rating 3 has the maximum counts.The gender-based performance is nearly same for both.
The employee not leaving the company is higher.

- Data Science: The performance rating 3 has the maximum counts in data science department. Data science is the only department where less number of level 2 performers and level 1 performers are present.Male employees are performing well. The employees not leaving the company is higher and the data science is the department which has a overall performance better than the other cdepartments.

- Research & Development: The performance rating 3 has the maximum counts. The female employees has higher performance rating than the males. The employees not leaving the company is higher

- Finance: The performance rating 3 has the maximum counts. The male employees has higher performance rating than the males. The employees not leaving the company is higher.


- In all the departments the age of the employees doesn't exceed 40 years.
- The department which has the youngest employees is the Development department.

In the visualization notebook, it was visualized that these three features plays an important role in determining the performance rating of the employees.
- EmpLastSalaryHikePercent
- EmpEnvironmentSatisfaction
- YearsSinceLastPromotion


**Mean distribution of the entire data**
- The entire data as a whole is normally distributed.
- The mean value is nearly 9 to 9.5
- From the graph it can be concluded that most of the data lies between 8 to 12 and the range is 4 to 20.

**Median distribution of the entire data**
- The entire data as a whole is normally distributed.
- the range is from 0 to 8
- Maximum of the data lies between 2 to 4 which is considered as the median or the middle value.


**Standard Deviation distribution of entire data**
- Distribution of standard deviation of data also look like guassian distribution around 30% of feature standard deviation around the range of 3 3 to 20 and remaining 70% feature standard deviation in between 0 to 2.

**Skewness and kurtosis of the data**

- Skewness is a measurement of the distortion of symmetrical distribution or asymmetry in a data set. Skewness is demonstrated on a bell curve when data points are not distributed symmetrically to the left and right sides of the median on a bell curve. If the bell curve is shifted to the left or the right, it is said to be skewed.
- Kurtosis is a measure of the tailedness of a distribution. Tailedness is how often outliers occur.
- There are different types of kurtosis- 
- A mesokurtic distribution is medium-tailed, so outliers are neither highly frequent, nor highly infrequent.

- Feature skewness was checked using statistical method and it was found that the feature **Year Since Last Promotion Feature**, **Total Work Experiance In Year Feature** and **Experiance Year At This Company Feature** have skewed data as the value among the other features is higher so we need to do feature transformation in data preprocessing.
- Feature transformation is done in features which has skewness of more than 1.
- The Skewness of Year Since Last Promotion Feature : 1.9749315589155791
- The kurtosis of Year Since Last Promotion Feature : 3.5390800793468817

- The Skewness of Total Work Experiance In Year Feature : 1.0868618597364565
- The kurtosis of Total Work Experiance In Year Feature : 0.8056333333819827

- The Skewness of Experiance Year At This Company Feature : 1.789054979919473
- The kurtosis of Experiance Year At This Company Feature : 4.057959404441291

- Since these features has skewness more than 1 so square root transformation was used for better performance.


# DATA PRE-PROCESSING

- The data pre-processing was done by handling the outliers,Categorical encoding,Feature Transformation,Feature scaling using MinMaxScaler,Checking for feature correlation,Feature Importance.

**Handling outliers-**
- The plot i.e Boxplot was used to detect the outliers.The features TotalWorkExperienceInYears,ExperienceYearsAtThisCompany and YearsSinceLastPromotion was selected for the outlier handling because the rest of the features are discrete features.
- Since, the above mentioned features are skewed distribution so median is used for the outlier handling and the method used is IQR.

**Categorical encoding**
- Encoding categorical data is a process of converting categorical data into integer format so that the data with converted categorical values can be provided to the models to give and improve the predictions.
- A structured data contains multiple columns with both numerical and categorical features.It is important to convert the categorical features into numerical features because the machine are incapable of understanding text.Instead they can only understand numbers.
- **One hot encoding** - One-hot encoding in machine learning is the conversion of categorical information into a format that may be fed into machine learning algorithms to improve prediction accuracy.
- **Label Encoding** - Label Encoding refers to converting the labels into a numeric form so as to convert them into the machine-readable form. Machine learning algorithms can then decide in a better way how those labels must be operated. It is an important pre-processing step for the structured dataset in supervised learning.Each label is assigned a unique integer based on alphabetical ordering.

- **CONVERTING THE MULTICLASS CLASSIFICATION TASK INTO BINARY CLASSIFICATION TASK**

**Feature Transformation**
- Function transformers are the type of feature transformation technique that uses a particular function to transform the data to the normal distribution
- In this project square root transformation technique was used for better performance.


The feature **Year Since Last Promotion Feature**, **Total Work Experiance In Year Feature** and **Experiance Year At This Company Feature** have skewed data so feature transformation was done.

**Dropping the features**

**ExperienceYearsAtThisCompany,YearsSinceLastPromotion,TotalWorkExperienceInYears,EmpNumber was dropped because new column i.e squ_YearsSinceLastPromotion, squ_TotalWorkExperienceInYears,squ_ExperienceYearsAtThisCompany was created***

**Feature scaling by StandardScaler**
- In Machine Learning, StandardScaler is used to resize the distribution of values so that the mean of the observed values is 0 and the standard deviation is 1.
- All the features except the target feature is not scaled.

**checking for correlation-**
- In this data no correlation was found between the data.
- PCA technique was not used as the performance of the model was low because PCA is performed when the features are highly correlated to each other, but as per the data it doesn't have nay correlation.



# Model Creation and Evaluation of Testing data and training data.

**AIM OF MODEL CREATION AND EVALUATION**
To create a generalised model having low bias and low variance

**low bias means low training error**

**low variance means low testing error**

- The pre-processed data was loaded and read.
- Defining the independent features and the dependent feature.
- Spliting the dataset into training and testing data.
- here 75% of the data is used for training and 25% of the data is used for testing.
- Balancing the data using SMOTE.

**SMOTE**

- SMOTE stands for Synthetic Minority Oversampling Technique.
- It is a statistical technique for increasing the number of cases in the dataset in a balanced way. The component works by generating new instances from existing minority cases that you supply as input.
- SMOTE works by utilizing a k-nearest neighbour algorithm to create synthetic data.
- SMOTE first starts by choosing random data from the minority class, then k-nearest neighbors from the data are set.
- It is done when the dataset is imbalance in case of Classification task.

**ALGORITHMS**
- The word Algorithm means ” A set of finite rules or instructions to be followed in calculations or other problem-solving operations.

**ALGORITHMS USED**
- Logistic Regression
- Support Vector Machine(Classifier)
- Support Vector Machine(Classifier)-Hyperparameter tuning.
- K-Nearest Neighbour(Classifier)
- K-Nearest Neighbour(Bagging)-Ensemble technique.
- Decision Tree(Classifier)
- Decision Tree(Classifier)-Hyperparameter tuning.
- Random Forest.
- Random Forest-Hyperparameter tuning
- Gradient Bossting- Boosting Technique.
- Artificial Neural Network.

**Best Algorithms for the given task**

**Support Vector Machine(calssifier)**
- Support Vector Machine or SVM is one of the most popular Supervised Learning algorithms, which is used for Classification as well as Regression problems. However, primarily, it is used for Classification problems in Machine Learning.
- The goal of the SVM algorithm is to create the best line or decision boundary that can segregate n-dimensional space into classes so that we can easily put the new data point in the correct category in the future. This best decision boundary is called a hyperplane.
- It works best on smaller datasets.

**Decision tree(Classifier)[TUNED]**
- A decision tree is a non-parametric supervised learning algorithm, which is utilized for both classification and regression tasks. It has a hierarchical, tree structure, which consists of a root node, branches, internal nodes and leaf nodes.
- Practically decision tree with smaller dataset overfits so decision tree tuned worked well in this dataset.

**Random Forest(Classifier)[TUNED]**
- It is an Ensembled technique
- Random forest is a commonly uses machine learning algorithm which combines the output of multiple decision trees to reach a single result.

**Gradient boosting**
- Gradient boosting is one of the variants of ensemble methods where you create multiple weak models and combine them to get better performance.


# Challenges Faced

- Smaller dataset but complex dataset.
- Conversion of multi-class classification task to binary classification for easy model evaluation.
- Various trial and error was done with the dataset by using PCA techniques and also by outlier handling of all the features.But the scores were not up to the mark so PCA was not included so only selected features were selected based on the feature importance for handling outliers thus resulting in good performance of the model i.e generalised model.
- Initially no transformation was done and checked the performance score of the model which resulted in a worst performance so in order to improve the model's overall score square root transformation was used.
- Data preprocessing and data exploration.
- To select a best model was also a challege.

# Reference

The References used for completing this project are-
- **AnalyticsVidya.com**
- **https://www.enjoyalgorithms.com/blog/univariate-bivariate-multivariate-analysis**
- **Coursera.com****
- **jstor.com****
- **performyard.com**

All of the above mentioned sites helped me in understanding the concepts and also helped me in successfully completing the project on time.